name: LMS CI/CD Pipeline

on:
  push:
    branches: [ "homework/34-deploy-github-actions", "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install linting tools
        run: pip install flake8
      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  tests:
    needs: linting
    runs-on: ubuntu-latest

    # Добавляем сервисы для тестов
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: lms_db
          POSTGRES_USER: lms_user
          POSTGRES_PASSWORD: lms_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: python manage.py test
        env:
          # Эти переменные должны совпадать с сервисом выше
          SECRET_KEY: "test_secret_key"
          DEBUG: "True"
          POSTGRES_DB: lms_db
          POSTGRES_USER: lms_user
          POSTGRES_PASSWORD: lms_password
          DB_HOST: localhost
          DB_PORT: 5432
          REDIS_HOST: localhost
          REDIS_PORT: 6379

  docker_build_check:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker images (dry run)
        run: docker compose build

  deploy:
    needs: docker_build_check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/homework/34-deploy-github-actions'
    steps:
      - uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "~/lms_project_docker"

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/lms_project_docker
            sudo docker compose down
            sudo docker compose up -d --build
            sudo docker compose exec -T backend python manage.py migrate
            sudo docker compose exec -T backend python manage.py collectstatic --noinput