name: CI/CD Pipeline

on:
  push:
    branches: [ "homework/34-deploy-github-actions", "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test
        env:
          SECRET_KEY: "test_secret_key"
          DEBUG: "True"
          DB_HOST: "localhost" # Для тестов используем sqlite по умолчанию или мок
          REDIS_HOST: "localhost"

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/homework/34-deploy-github-actions' # Деплоим только из этой ветки
    steps:
      - uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "~/lms_project_docker"

      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/lms_project_docker
            sudo docker compose down
            sudo docker compose up -d --build
            sudo docker compose exec -T backend python manage.py migrate
            sudo docker compose exec -T backend python manage.py collectstatic --noinput